# Generated by Django 3.1.3 on 2020-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('rut', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('rut_dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
