# Generated by Django 3.1.3 on 2020-11-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuario',
        ),
    ]
